#!/usr/bin/python3
def raise_exception():
    result = 2 + "Error"
    return result
